In [3]:
# Kennedi Todd
# July 31, 2024
# k-Nearest Neighbors
# Classify penguin based on variables
# https://scatterplotpress.teachable.com/p/ml-code-exercises

# libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix

# read data
df = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/penguins.csv')
df.head()

# delete sex variable, don't want binary variables
del df['sex']

# drop row with missing values
df.dropna(axis = 0,        # 0 = row, 1 = column
          how = 'any',     # drop rows if at least one value missing
          subset = None,   # use all columns
          inplace = True)  # update rather than replace

# one-hot encoding
df = pd.get_dummies(df, columns = ['island']) # species is the dependent var
df.head()

,species,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,island_Biscoe,island_Dream,island_Torgersen
0,Adelie,39.1,18.7,181.0,3750.0,False,False,True
1,Adelie,39.5,17.4,186.0,3800.0,False,False,True
2,Adelie,40.3,18.0,195.0,3250.0,False,False,True
4,Adelie,36.7,19.3,193.0,3450.0,False,False,True
5,Adelie,39.3,20.6,190.0,3650.0,False,False,True

In [4]:
# standardize the independent vars
scaler = StandardScaler()
scaler.fit(df.drop('species', axis = 1))
scaled_df = scaler.transform(df.drop('species', axis = 1))

# assign vars
X = scaled_df
y = df['species']

# split into testing/training
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, shuffle = True)

# assign algorithm
model = KNeighborsClassifier(n_neighbors = 4)

# train
model.fit(X_train, y_train)

# make prediction
model_test =  model.predict(X_test)

# evaluate
print(confusion_matrix(y_test, model_test))
print(classification_report(y_test, model_test))

[[47  0  0]
 [ 1 21  0]
 [ 0  0 34]]
              precision    recall  f1-score   support

      Adelie       0.98      1.00      0.99        47
   Chinstrap       1.00      0.95      0.98        22
      Gentoo       1.00      1.00      1.00        34

    accuracy                           0.99       103
   macro avg       0.99      0.98      0.99       103
weighted avg       0.99      0.99      0.99       103

In [5]:
# predict data point
penguin = [
    39,   # bill length
    18.5, # bill depth
    180,  # flipper length
    3750, # body mass
    0,    # island Biscoe
    0,    # island Dream
    1,    # island Torgersen
]
predict_penguin = model.predict([penguin])
predict_penguin

array(['Gentoo'], dtype=object)